EXP:
    ID: jointbksv2
    OUTPUT_DIR: data
    VARIANT_NAME: upsample_none

DATASET:
    LABELS: ./data/datasets/human/labels.txt
    N_CLASSES: 2

TRAIN_DATASETS:
      - NAME: atr
        ROOT: /home/mscv1/Desktop/FRL/human_parsing_datasets/ATR/humanparsing
        LABELS: ./data/datasets/human/labels.txt
        N_CLASSES: 2
        IGNORE_LABEL: 255
        SCALES: [1.0, 1.5, 2.0]
        SPLIT: # None
      
      - NAME: lip
        ROOT: /home/mscv1/Desktop/FRL/human_parsing_datasets/LIP
        LABELS: ./data/datasets/human/labels.txt
        N_CLASSES: 2
        IGNORE_LABEL: 255
        SCALES: [0.6, 0.8, 1.0]
        SPLIT: trainval
      
      - NAME: cihp
        ROOT: /home/mscv1/Desktop/FRL/human_parsing_datasets/CIHP/instance-level_human_parsing
        LABELS: ./data/datasets/human/labels.txt
        N_CLASSES: 2
        IGNORE_LABEL: 255
        SCALES: [1.0, 1.5, 2.0]
        SPLIT: trainval
    
BG_DATASET_ROOT: /home/mscv1/Desktop/FRL/synthetic_bgs
SYN_RATIO: 0.5
GET_RAW_ITEM: true
GRAY_AUG: false
BG_SCALES: [0.5, 0.75, 1.0]
BRIGHTNESS_RANGE: [0.5, 1.2]
VIS_ITER: 1000
VAL_ITER: 500
TRAIN_ALL_GRAY: true
UPSAMPLER_MODE: none

DATALOADER:
    NUM_WORKERS: 4

IMAGE:
    MEAN:
        R: 122.675
        G: 116.669
        B: 104.008
    SIZE:
        BASE: 513
        TRAIN: 321
        TEST: 2048

MODEL:
    NAME: DeepLabV2_ResNet101_MSC
    N_BLOCKS: [3, 4, 23, 3]
    ATROUS_RATES: [6, 12, 18, 24]
    INIT_MODEL: data/models/coco/deeplabv1_resnet101/caffemodel/deeplabv1_resnet101-coco.pth
    N_CLASSES: 2

SOLVER:
    BATCH_SIZE:
        TRAIN: 16
        TEST: 1
    ITER_MAX: 300000
    ITER_SIZE: 1
    ITER_SAVE: 1000
    ITER_TB: 50
    LR_DECAY: 10
    LR: 5.0e-4
    MOMENTUM: 0.9
    OPTIMIZER: sgd
    POLY_POWER: 0.9
    WEIGHT_DECAY: 5.0e-4
    AVERAGE_LOSS: 20
    IGNORE_LABEL: 255

CRF:
    ITER_MAX: 10
    POS_W: 3
    POS_XY_STD: 1
    BI_W: 4
    BI_XY_STD: 67
    BI_RGB_STD: 3
